# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# ===================================================================
server:
  port: 8081

logging:
  level:
    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    com.blank.project: DEBUG

spring:
  devtools:
    restart:
      enabled: false
      additional-exclude: static/**,.h2.server.properties
  jackson:
    serialization:
      indent-output: true
  datasource:
    platform: postgresql
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blank_project
    username: postgres
    password: postgres
    minimum-idle: 10 # The minimum number of established connections that should be kept in the pool at all times.
    maximum-pool-size: 50 # The maximum number of connections that should be kept in the pool at all times.
    idle-timeout: 30000 # The maximum amount of time in milliseconds that a connection is allowed to sit idle in connection pool
    max-lifetime: 60000 # The maximum lifetime of a connection in the pool
    initialization-mode: always
    continue-on-error: false
  h2:
    console:
      # disable spring boot built-in h2-console since we start it manually with correct configuration
      enabled: false
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: blank
  liquibase:
    enabled: true
    default-schema: blank
    change-log: classpath:config/liquibase/master.xml
  thymeleaf:
    cache: false

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    displayRequestDuration: true
    disable-swagger-default-url: true
    csrf:
      enabled: true
    operationsSorter: method #For sorting endpoints by http methods
    tagsSorter: alpha #For sorting tags alphabetically
  api-docs:
    path: /api
    enabled: true